fix: use absolute URL for logo in email
Requarks/wiki pull request #2628
Opened 2020-10-27 22:28 UTC by EricFromCanada

Prepends the wiki site URL to the logo path used when sending email from the wiki.

Before: `<img src="/uploads/logo.png"`
After: `<img src="http://wiki.site.url/uploads/logo.png`

2020-11-01 18:02 UTC, NGPixel requested changes

2020-11-01 18:02 UTC, NGPixel commented on server/core/mail.js
> +        logo: WIKI.config.host + WIKI.config.logoUrl,
logoUrl can also be an absolute URL. There should be a check to see whether logoUrl starts with http and only prefix the host if not.

2020-11-10 18:40 UTC, EricFromCanada commented
Added a ternary that conditionally prepends the host URL. Tested both cases on my installation.

2020-11-11 16:38 UTC, NGPixel approved these changes

2020-11-11 16:39 UTC, merged