Feature: Custom configuration for elasticsearch
Requarks/wiki pull request #2793
Opened 2020-12-07 13:17 UTC by scienceasdf

For better search results especially in Chinese, which the standard token analyzer may not work well. In Chinese, the adminstrator may need to set the token analyzer to smartcn, itk, etc. This PR adds the elastic analyzer configuration to the search module.

2020-12-08 18:26 UTC, NGPixel requested changes

2020-12-08 18:26 UTC, NGPixel commented on server/modules/search/elasticsearch/engine.js
> +            },
Remove dangling comma

2020-12-09 02:27 UTC, scienceasdf commented on server/modules/search/elasticsearch/engine.js
> +            },
Fix that

2020-12-09 02:41 UTC, NGPixel approved these changes

2020-12-09 02:41 UTC, merged