Add possibility to set PostgreSQL Schema other than public
Requarks/wiki pull request #4161
Opened 2021-07-04 13:30 UTC by fredericalix

I wanted the possibility to use another pg schema than public.

2021-07-04 21:43 UTC, NGPixel requested changes

2021-07-04 21:43 UTC, NGPixel commented on config.sample.yml
> +  schema: public # Only for choice a PostgreSQL Schema other than public
Put lower down (before sqlite storage option), with comment:
```yaml
# Optional - PostgreSQL only:
schema: public
```

2021-07-04 21:43 UTC, NGPixel commented on server/core/db.js
> +                  if (database_schema != 'public') {
Use instead:

```
if (WIKI.config.db.schema && WIKI.config.db.schema !== 'public') {
```

and remove the var declaration above.

2021-09-25 02:56 UTC, NGPixel approved these changes

2021-09-25 02:56 UTC, merged

2022-11-17 10:51 UTC, jsprds commented
Hi @fredericalix, can I set the pg schema with an ENV variable? Thanks! 🙏