feat(helm): allow usage of additional env vars / configmap / secrets
requarks/wiki pull request #6204
Opened 2023-02-24 16:32 UTC by MickaelCa

This PR makes it possible to load external environmenent variables.
On my cluster, I'm using [Postgres Operator](https://access.crunchydata.com/documentation/postgres-operator/latest/) by CrunchyData, I need to be able to load the generated database secrets directly rather than copying it in the values.

2023-02-26 20:07 UTC, bdsoha commented on dev/helm/values.yaml
> +  configmaps: []
IMO, this should be camelCase, as it is found in the k8s API *(`configMapRef`)*.

```suggestion
  configMaps: []
```

2023-02-26 20:07 UTC, bdsoha commented on dev/helm/templates/deployment.yaml
> +            {{- with .Values.extraEnv.configmaps }}
```suggestion
            {{- with .Values.extraEnv.configMaps }}
```

2023-02-26 20:07 UTC, bdsoha requested changes
IMO, this should be camelCase, as it is found in the k8s API *(`configMapRef`)*.

2023-03-18 23:08 UTC, stavros-k commented on dev/helm/templates/deployment.yaml
> +            {{- if .Values.postgresql.enabled}}
```suggestion
            {{- if .Values.postgresql.enabled }}
```

2023-03-18 23:08 UTC, stavros-k commented on dev/helm/templates/deployment.yaml
> +            {{- with .Values.extraEnv.env }}
I'd suggest checking if `extraEnv` is not null first.
On upgrade, it won't exist in values.yaml and will most likely error with `{}.env` `nil` pointer.

2024-05-21 15:15 UTC, closed without merging